### ISSUE TITLE
Link to aur is broken

### ISSUE THREAD

**Issue by Strykar** [Irvinehimself/ArchAudit-Report#1]
Is this not available on aur anymore?
https://aur.archlinux.org/packages/?O=0&K=ArchAudit-Report

**Comment by Irvinehimself** [comment]
Sorry, I was away from Arch for a while and unable to maintain <u>any</u> AUR packages, as a result it seemed best to just remove it. I believe the following is the correct package build:

    pkgname=archaudit-report
    pkgver=1.05
    pkgrel=1
    pkgdesc="Report on applications with inherited security advisories"
    arch=('any')
    url="https://github.com/Irvinehimself/ArchAudit-Report"
    license=('GPL3')
    depends=('arch-audit' 'pkgtools')
    source=("https://github.com/Irvinehimself/ArchAudit-Report/archive/1.05.tar.gz")
    sha256sums=("90c80802e0a21d4f948348433e43895863e513f568719ee8cdb81059e425322d")
    
    package() {
        cd "${srcdir}/ArchAudit-Report-$pkgver"
        install -Dm755 $pkgname "$pkgdir/usr/bin/$pkgname"
    }

Alternatively, it's just a single file, so it could  be easily installed to `/usr/local/bin`

Irvine

**Comment by Strykar** [comment]
So are you back to using Arch or should this be considered abandoned?

**Comment by Irvinehimself** [comment]
At the moment, I am not quite sure where things are going. Since recently returning to Arch, I have been reviewing and rebuilding my main hardening project from the ground up. As far as ArchAudit-Report is concerned, the project is not so much *abandoned*, as *on-hold*.

Irvine

**Comment by Strykar** [comment]
Thanks for clearing that up, closing.
